version = 0.1
[default.deploy.parameters]
stack_name = "mariana-pereira-sqs"
resolve_s3 = false
s3_prefix = "mariana-pereira-sqs"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
