AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Hello World

Resources:
  SqsQueue:
    Type: AWS::SQS::Queue
  Producer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/producer
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          URL_QUEUE: !GetAtt SqsQueue.QueueUrl
          QUEUE_NAME: !GetAtt SqsQueue.QueueName
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt SqsQueue.QueueName
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /producer
            Method: post
  Consumer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/consumer
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        SqsQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt SqsQueue.Arn
            BatchSize: 10